name: core
description: "A new Flutter project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  graphql_flutter: ^5.1.2
  intl: ^0.18.1
  http: ^1.2.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio_http2_adapter: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  freezed: ^2.5.2
  json_serializable: ^6.7.1

flutter:
