name: atomic_design
description: A TOT Platform Atomic Design Package.
version: 0.0.1+1
publish_to: "none"

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  fl_chart: ^0.67.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: ^0.18.1
  shimmer: ^3.0.0
  fluentui_system_icons: ^1.1.223
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  syncfusion_flutter_core: ^25.1.38
  syncfusion_flutter_sliders: ^25.1.38
  gap: ^3.0.1
  flutter_hooks: ^0.20.3
  fluttertoast: ^8.2.4
  flutter_staggered_grid_view: ^0.7.0
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^3.0.1

  core:
    git:
      url: https://github.com/TOTPLATFORM/mobile-layers.git
      path: packages/core
      ref: dev

  application:
    git:
      url: https://github.com/TOTPLATFORM/mobile-layers.git
      path: packages/application
      ref: dev

  vector_math: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: 2.4.7

# dependency_overrides:
#   fl_chart:
flutter:
  uses-material-design: true
  # generate: true

  assets:
    - assets/images/image_placeholder.svg
