name: domain
description: "A new Flutter project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  core:
    git:
      url: https://github.com/TOTPLATFORM/mobile-layers.git
      path: packages/core
      ref: dev

  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  freezed: ^2.5.2
  json_serializable: ^6.7.1

flutter:
